export default [
  {
    title: 'First Shirt',
    previewText: 'This is the preview text',
    imgUrl: 'https://source.unsplash.com/random',
    id: 'our-first-shirt',
    price: 29.99,
  },
  {
    title: 'First Shirt',
    previewText: 'This is the preview text',
    imgUrl: 'https://source.unsplash.com/random',
    id: 'our-first-shirt',
    price: 29.99,
  },
  {
    title: 'First Shirt',
    previewText: 'This is the preview text',
    imgUrl: 'https://source.unsplash.com/random',
    id: 'our-first-shirt',
    price: 29.99,
  },
  {
    title: 'First Shirt',
    previewText: 'This is the preview text',
    imgUrl: 'https://source.unsplash.com/random',
    id: 'our-first-shirt',
    price: 29.99,
  },
  {
    title: 'First Shirt',
    previewText: 'This is the preview text',
    imgUrl: 'https://source.unsplash.com/random',
    id: 'our-first-shirt',
    price: 29.99,
  },
  {
    title: 'First Shirt',
    previewText: 'This is the preview text',
    imgUrl: 'https://source.unsplash.com/random',
    id: 'our-first-shirt',
    price: 29.99,
  },
  {
    title: 'First Shirt',
    previewText: 'This is the preview text',
    imgUrl: 'https://source.unsplash.com/random',
    id: 'our-first-shirt',
    price: 29.99,
  },
  {
    title: 'First Shirt',
    previewText: 'This is the preview text',
    imgUrl: 'https://source.unsplash.com/random',
    id: 'our-first-shirt',
    price: 29.99,
  },
  {
    title: 'First Shirt',
    previewText: 'This is the preview text',
    imgUrl: 'https://source.unsplash.com/random',
    id: 'our-first-shirt',
    price: 29.99,
  },
];
